
'use client';

import { forwardRef } from 'react';
import type { Transaction } from '@/lib/types';
import { ShoppingBag } from 'lucide-react';

interface PrintableReceiptProps {
  transaction: Transaction;
}

const PrintableReceipt = forwardRef<HTMLDivElement, PrintableReceiptProps>(({ transaction }, ref) => {
  return (
    <div ref={ref} className="p-8 font-sans text-black bg-white">
        <div className="text-center mb-8">
            <div className="flex items-center justify-center gap-3">
                 <ShoppingBag className="h-8 w-8 text-black" />
                <h1 className="text-3xl font-bold">Campus Cart</h1>
            </div>
            <p className="text-sm">Transaction Receipt</p>
        </div>
        
        <div className="mb-6">
            <p><strong>Transaction ID:</strong> {transaction.id}</p>
            <p><strong>Date:</strong> {new Date(transaction.date).toLocaleDateString()}</p>
            <p><strong>Vendor:</strong> {transaction.vendorName}</p>
        </div>

        <table className="w-full mb-6">
            <thead>
                <tr className="border-b-2 border-black">
                    <th className="text-left py-2">Item</th>
                    <th className="text-center py-2">Quantity</th>
                    <th className="text-right py-2">Price</th>
                    <th className="text-right py-2">Total</th>
                </tr>
            </thead>
            <tbody>
                {transaction.items.map((item, index) => (
                    <tr key={index} className="border-b border-gray-300">
                        <td className="py-2">{item.name}</td>
                        <td className="text-center py-2">{item.quantity}</td>
                        <td className="text-right py-2">₹{item.price.toFixed(2)}</td>
                        <td className="text-right py-2">₹{(item.price * item.quantity).toFixed(2)}</td>
                    </tr>
                ))}
            </tbody>
        </table>

        <div className="flex justify-end">
            <div className="w-1/3">
                <div className="flex justify-between font-bold text-lg">
                    <span>Grand Total</span>
                    <span>₹{transaction.total.toFixed(2)}</span>
                </div>
            </div>
        </div>

        <div className="text-center mt-12 text-sm text-gray-600">
            <p>Thank you for your purchase!</p>
            <p>Generated by Campus Cart</p>
        </div>
    </div>
  );
});

PrintableReceipt.displayName = 'PrintableReceipt';
export default PrintableReceipt;
